# Generated by Django 4.1.2 on 2022-11-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calculator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "execution_time",
                    models.CharField(max_length=240, verbose_name="execution_time"),
                ),
                ("x1", models.CharField(max_length=240, verbose_name="x1")),
                ("x2", models.CharField(max_length=240, verbose_name="x2")),
                ("fit_fun", models.CharField(max_length=240, verbose_name="fit_fun")),
                (
                    "problem_to_solve",
                    models.CharField(max_length=240, verbose_name="fit_fun"),
                ),
                ("variation", models.CharField(max_length=240, verbose_name="fit_fun")),
            ],
        ),
        migrations.CreateModel(
            name="CalculatorResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "saved_result_record_id",
                    models.CharField(max_length=240, verbose_name="x1"),
                ),
                ("x1", models.CharField(max_length=240, verbose_name="x1")),
                ("x2", models.CharField(max_length=240, verbose_name="x2")),
                ("fit_fun", models.CharField(max_length=240, verbose_name="fit_fun")),
                ("variation", models.CharField(max_length=240, verbose_name="fit_fun")),
            ],
        ),
    ]
