# Generated by Django 4.1.2 on 2022-11-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calculator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "begin_of_range",
                    models.CharField(max_length=240, verbose_name="begin_of_range"),
                ),
                ("created", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
