import { FormEvent, Dispatch, SetStateAction } from 'react';

export type initialCalculationDataFormType = {
  onFormSubmit: (e: FormEvent) => void;
  beginOfrRange: string;
  setBeginOfRange: Dispatch<SetStateAction<string>>;
  endOfRange: string;
  setEndOfRange: Dispatch<SetStateAction<string>>;
  populationMembersCount: string;
  setPopulationMembersCount: Dispatch<SetStateAction<string>>;
  epochsCount: string;
  setEpochsCount: Dispatch<SetStateAction<string>>;
  chromosomCount: string;
  setChromosomCount: Dispatch<SetStateAction<string>>;
  eliteStrategyCount: string;
  setEliteStrategyCount: Dispatch<SetStateAction<string>>;
  inversionProbability: string;
  setInversionProbability: Dispatch<SetStateAction<string>>;
  mutationProbability: string;
  setMutationProbability: Dispatch<SetStateAction<string>>;
  crossProbablility: string;
  setCrossProbablility: Dispatch<SetStateAction<string>>;
  bitsCount: string;
  setBitsCount: Dispatch<SetStateAction<string>>;
  selectionMethod: string;
  setSelectionMethod: Dispatch<SetStateAction<string>>;
  crossMethod: string;
  setCrossMethod: Dispatch<SetStateAction<string>>;
  mutationMethod: string;
  setMutationMethod: Dispatch<SetStateAction<string>>;
};
